apiVersion: v1
kind: Pod
metadata:
  name: buildkitd-pod-http-project
  annotations:
    container.apparmor.security.beta.kubernetes.io/buildkitd-http-project: unconfined
spec:
  containers:
    - name: buildkitd-http-project
      image: moby/buildkit:master-rootless
      env:
      - name: "DOCKER_CONFIG"
        value: "/home/.docker"
      args:
        - --oci-worker-no-process-sandbox
      resources:
        requests:
          memory: 1024Mi
          cpu: 1000m
        limits:
          memory: 2048Mi
          cpu: 2000m
      readinessProbe:
        exec:
          command:
            - buildctl
            - debug
            - workers
        initialDelaySeconds: 5
        periodSeconds: 30
      livenessProbe:
        exec:
          command:
            - buildctl
            - debug
            - workers
        initialDelaySeconds: 5
        periodSeconds: 30
      securityContext:
        seccompProfile:
          type: Unconfined
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: docker-auth-secret
          mountPath: /home/.docker
        - name: buildkitd-http-project
          mountPath: /home/user/.local/share/buildkit
  volumes:
    - name: docker-auth-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: buildkitd-http-project
      emptyDir: {}
